apts = [
        {"id": "6891076443",
         "repost_of": None, 
         "name": "Available July Studio , includes all Notre-Dame-de-Grace", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-available-july-studio-includes/6891076443.html", 
         "datetime": "2019-05-21 23:57", 
         "price": "$940", 
         "where": "Notre-Dame-de-Grace", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "1", 
         "area": None},
        {"id": "6892879812", 
         "repost_of": None, 
         "name": "Downtown 2 1/2 Fully Furnished", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-downtown-fully-furnished/6892879812.html", 
         "datetime": "2019-05-21 23:52", 
         "price": "$1325", 
         "where": None, 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": None, 
         "area": None},
        {"id": "6894520397", 
         "repost_of": None, 
         "name": "3 1/2 sunny renovated basement appartement", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-sunny-renovated-basement/6894520397.html", 
         "datetime": "2019-05-21 23:16", 
         "price": "$700", 
         "where": "NDG", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "1", 
         "area": None},
        {"id": "6894518491", 
         "repost_of": None, 
         "name": "4 1/2 Condo for Rent - Griffintown Lowney sur Ville", 
         "url": "https://montreal.craigslist.org/apa/d/griffintown-condo-for-rent-griffintown/6894518491.html", 
         "datetime": "2019-05-21 23:11", 
         "price": "$2000", 
         "where": "Montreal", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "2", 
         "area": "651ft2"},
        {"id": "6880067690", 
         "repost_of": "6568316721", 
         "name": "Lovely upper 7 1/2 room apt, 4 Br 2 BthRms garage heat hot water", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-lovely-upper-room-apt-4-br-2/6880067690.html", 
         "datetime": "2019-05-21 23:04", 
         "price": "$2390", 
         "where": "Outremont - CDN- Cotes des Neiges", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "4", 
         "area": "1850ft2"},
        {"id": "6894515099", 
         "repost_of": None, 
         "name": "Charmant 3 et 1/2 enti\u00e8rement meubl\u00e9 \u00e0 louer", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-charmant-3-et-1-2-entirement/6894515099.html", 
         "datetime": "2019-05-21 23:02", 
         "price": "$1175", 
         "where": "5175 6e Avenue, Vieux Rosemont", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "1", 
         "area": None},
        {"id": "6894514380", 
         "repost_of": None, 
         "name": "Appartement 2 1/2 Cuisine s\u00e9par\u00e9e (m\u00e9tro Cadillac)", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-appartement-cuisine-spare-mtro/6894514380.html", 
         "datetime": "2019-05-21 23:01", 
         "price": "$660", 
         "where": "2666 rue de Cadillac, Montreal, QC", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "1", 
         "area": "450ft2"},
        {"id": "6894512959", 
         "repost_of": None, 
         "name": "House/Apartment for Rent", 
         "url": "https://montreal.craigslist.org/apa/d/montreal-house-apartment-for-rent/6894512959.html", 
         "datetime": "2019-05-21 22:57", 
         "price": "$1200", 
         "where": "Close to Metro Parc", 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "3", 
         "area": None},
        {"id": "6879161907", 
         "repost_of": "6587857195", 
         "name": "Beautiful spacious 4 bedroom high ceiling condo durocher outremont", 
         "url": "https://montreal.craigslist.org/apa/d/outremont-beautiful-spacious-4-bedroom/6879161907.html", 
         "datetime": "2019-05-21 22:45", 
         "price": "$2175", 
         "where": None, 
         "has_image": False, 
         "has_map": False, 
         "geotag": None, 
         "bedrooms": "4", 
         "area": "1300ft2"}]

